site_name: 冰与火之歌
nav:
    - Home: index.md
    - 权利的游戏:
        - 000 序: 权利的游戏/000-序.md
        - 001 布兰: 权利的游戏/001-布兰.md
        - 003 凯特琳: 权利的游戏/003-凯特琳.md
        - 004 丹妮莉丝: 权利的游戏/004-丹妮莉丝.md
        - 005 艾德: 权利的游戏/005-艾德.md
        - 006 琼恩: 权利的游戏/006-琼恩.md
        - 007 凯特琳: 权利的游戏/007-凯特琳.md
        - 008 艾莉亚: 权利的游戏/008-艾莉亚.md
        - 009 布兰: 权利的游戏/009-布兰.md

theme:
    name: 'material'
